name: Modify Aleph Node Runtime

on:
  push:
    branches:
      - main # Change to your branch name if needed

jobs:
  modify_runtime:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Clone Aleph Node Repository
      run: |
        git clone https://github.com/WaterCoolerStudiosInc/kintsu-aleph-patch.git
        cd aleph-node
        git checkout r-11.4
      working-directory: ./aleph-node

    - name: Apply Patch
      run: |
        # Assuming you have 'call_runtime.patch' in your repository root
        git apply ../call_runtime.patch
      working-directory: ./aleph-node

    - name: Build Aleph Node
      run: |
        ./scripts/run_nodes.sh
      working-directory: ./aleph-node

    - name: Build Docker Image
      run: |
        docker build -t your-image-name:latest ./aleph-node
        docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
        docker push your-image-name:latest
      env:
        DOCKER_CLI_ACI_OFF: "1"

    - name: Cleanup
      run: |
        docker logout
      env:
        DOCKER_CLI_ACI_OFF: "1"
